-- Question 16 – Weekday vs Weekend Sales Analysis
-- Business Problem

-- The marketing team wants to understand customer purchasing behavior. 
-- Determine whether customers spend more on weekdays or weekends by calculating the total revenue generated in each group.

WITH day_ AS (
    SELECT
        total_amount,
        DAYNAME(STR_TO_DATE(order_date, '%m/%d/%Y')) AS day_name
    FROM data2
)

SELECT
    CASE
        WHEN day_name IN ('Saturday', 'Sunday') THEN 'Weekend'
        ELSE 'Weekday'
    END AS day_type,
    ROUND(SUM(total_amount), 2) AS total_revenue
FROM day_
GROUP BY day_type
ORDER BY total_revenue DESC;


-- Question 17 – Customer Acquisition Trend
-- Business Problem

-- The marketing department wants to analyze how many new customers were acquired each month.
--  A new customer is someone making their first-ever purchase.



WITH first_purchase AS (
    SELECT
        customer_id,
        MIN(STR_TO_DATE(order_date, '%m/%d/%Y')) AS first_order_date
    FROM data2
    GROUP BY customer_id
)

SELECT
    MONTHNAME(first_order_date) AS month_name,
    COUNT(customer_id) AS new_customers
FROM first_purchase
GROUP BY
    MONTH(first_order_date),
    MONTHNAME(first_order_date)
ORDER BY
    MONTH(first_order_date);
    

-- 18. Payment Method Revenue Analysis

-- Business Problem

-- The finance team wants to understand customer payment preferences.
--  Calculate the total revenue generated through each payment method and identify the most preferred payment option.


SELECT
    payment_method,
    ROUND(SUM(total_amount), 2) AS total_revenue
FROM data2
GROUP BY payment_method
ORDER BY total_revenue DESC;


-- 19. Regional Revenue Analysis

-- Business Problem

-- Management wants to identify the highest-performing regions. 
-- Calculate the total revenue generated by each region and rank them from highest to lowest.


SELECT
region,
    ROUND(SUM(total_amount), 2) AS total_revenue
FROM data2
GROUP BY region
ORDER BY total_revenue DESC;


-- 20. City-wise Sales Performance

-- Business Problem

-- The sales team wants to identify the cities generating the highest revenue. 
-- Calculate total sales for each city and rank the top-performing cities.


SELECT
city,
    ROUND(SUM(total_amount), 2) AS total_revenue
FROM data2
GROUP BY city
ORDER BY total_revenue DESC;



    
    
