
-- 1.What is the total revenue generated by the company?
SELECT SUM(total_amount) AS total_revenue
FROM ecommerce_merged_dataset;

-- 2.Which are the top 10 best-selling products based on quantity sold?

SELECT product_name,SUM(quantity) AS quantity_sold
FROM ecommerce_merged_dataset
GROUP BY product_name
ORDER BY quantity_sold DESC
LIMIT 10;

-- 3. Which product category generates the highest revenue?
SELECT category,SUM(total_amount) AS total_revenue
FROM ecommerce_merged_dataset
GROUP BY category
ORDER BY total_revenue DESC
limit 1;

-- 4.Which customers have spent the most money?
SELECT customer_id, customer_name,SUM(total_amount) AS total_spend
FROM ecommerce_merged_dataset
GROUP BY customer_id,customer_name
ORDER BY total_spend DESC
limit 10;

-- 5. What are the monthly sales trends over the last year?
    
    SELECT
    YEAR(STR_TO_DATE(order_date, '%m/%d/%Y')) AS year,
    MONTH(STR_TO_DATE(order_date, '%m/%d/%Y')) AS month,
    SUM(total_amount) AS total_sales
FROM ecommerce_merged_dataset
GROUP BY
    YEAR(STR_TO_DATE(order_date, '%m/%d/%Y')),
    MONTH(STR_TO_DATE(order_date, '%m/%d/%Y'))
ORDER BY
    year,
    month;
    















